### ISSUE TITLE
Module failure message

### ISSUE THREAD

**Issue by bjom8** [gmoisio/ansible-aos-stdlib#2]
Hello,

First of all, thank you for your content.

When running the playbooks, I am getting the next message:

ok: [10.77.166.9]
ok: [10.77.166.7]
ok: [10.77.166.8]
fatal: [10.77.166.11]: FAILED! => changed=false
  module_stderr: |-
    Unknown exception: module 'cryptography.utils' has no attribute 'bit_length'
    Traceback (most recent call last):
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/transport.py", line 2075, in run
        self.kex_engine.parse_next(ptype, m)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/kex_gex.py", line 101, in parse_next
        return self._parse_kexdh_gex_reply(m)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/kex_gex.py", line 281, in _parse_kexdh_gex_reply
        self.transport._verify_key(host_key, sig)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/transport.py", line 1886, in _verify_key
        if not key.verify_ssh_sig(self.H, Message(sig)):
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/dsskey.py", line 153, in verify_ssh_sig
        ).public_key(backend=default_backend())
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 212, in public_key
        return backend.load_dsa_public_numbers(self)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 873, in load_dsa_public_numbers
        dsa._check_dsa_parameters(numbers.parameter_numbers)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/netmiko/tplink/tplink_jetstream.py", line 145, in _override_check_dsa_parameters
        if crypto_utils.bit_length(parameters.q) not in [160, 256]:
    AttributeError: module 'cryptography.utils' has no attribute 'bit_length'

    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1603205497.7977629-91635-136141788041902/AnsiballZ_ale_aos_ping.py", line 102, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1603205497.7977629-91635-136141788041902/AnsiballZ_ale_aos_ping.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1603205497.7977629-91635-136141788041902/AnsiballZ_ale_aos_ping.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible.modules.ale_aos_ping', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_ale_aos_ping_payload_cousgmdf/ansible_ale_aos_ping_payload.zip/ansible/modules/ale_aos_ping.py", line 128, in <module>
      File "/tmp/ansible_ale_aos_ping_payload_cousgmdf/ansible_ale_aos_ping_payload.zip/ansible/modules/ale_aos_ping.py", line 114, in main
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 312, in ConnectHandler
        return ConnectionClass(*args, **kwargs)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/netmiko/base_connection.py", line 346, in __init__
        self._open()
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/netmiko/base_connection.py", line 351, in _open
        self.establish_connection()
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/netmiko/base_connection.py", line 920, in establish_connection
        self.remote_conn_pre.connect(**ssh_connect_params)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/client.py", line 406, in connect
        t.start_client(timeout=timeout)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/transport.py", line 660, in start_client
        raise e
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/transport.py", line 2075, in run
        self.kex_engine.parse_next(ptype, m)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/kex_gex.py", line 101, in parse_next
        return self._parse_kexdh_gex_reply(m)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/kex_gex.py", line 281, in _parse_kexdh_gex_reply
        self.transport._verify_key(host_key, sig)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/transport.py", line 1886, in _verify_key
        if not key.verify_ssh_sig(self.H, Message(sig)):
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/dsskey.py", line 153, in verify_ssh_sig
        ).public_key(backend=default_backend())
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 212, in public_key
        return backend.load_dsa_public_numbers(self)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 873, in load_dsa_public_numbers
        dsa._check_dsa_parameters(numbers.parameter_numbers)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/netmiko/tplink/tplink_jetstream.py", line 145, in _override_check_dsa_parameters
        if crypto_utils.bit_length(parameters.q) not in [160, 256]:
    AttributeError: module 'cryptography.utils' has no attribute 'bit_length'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
fatal: [10.77.166.12]: FAILED! => changed=false
  module_stderr: |-
    Unknown exception: module 'cryptography.utils' has no attribute 'bit_length'
    Traceback (most recent call last):
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/transport.py", line 2075, in run
        self.kex_engine.parse_next(ptype, m)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/kex_gex.py", line 101, in parse_next
        return self._parse_kexdh_gex_reply(m)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/kex_gex.py", line 281, in _parse_kexdh_gex_reply
        self.transport._verify_key(host_key, sig)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/transport.py", line 1886, in _verify_key
        if not key.verify_ssh_sig(self.H, Message(sig)):
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/dsskey.py", line 153, in verify_ssh_sig
        ).public_key(backend=default_backend())
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 212, in public_key
        return backend.load_dsa_public_numbers(self)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 873, in load_dsa_public_numbers
        dsa._check_dsa_parameters(numbers.parameter_numbers)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/netmiko/tplink/tplink_jetstream.py", line 145, in _override_check_dsa_parameters
        if crypto_utils.bit_length(parameters.q) not in [160, 256]:
    AttributeError: module 'cryptography.utils' has no attribute 'bit_length'

    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1603205498.4729698-91663-214155959802390/AnsiballZ_ale_aos_ping.py", line 102, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1603205498.4729698-91663-214155959802390/AnsiballZ_ale_aos_ping.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1603205498.4729698-91663-214155959802390/AnsiballZ_ale_aos_ping.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible.modules.ale_aos_ping', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_ale_aos_ping_payload_w49hriyt/ansible_ale_aos_ping_payload.zip/ansible/modules/ale_aos_ping.py", line 128, in <module>
      File "/tmp/ansible_ale_aos_ping_payload_w49hriyt/ansible_ale_aos_ping_payload.zip/ansible/modules/ale_aos_ping.py", line 114, in main
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 312, in ConnectHandler
        return ConnectionClass(*args, **kwargs)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/netmiko/base_connection.py", line 346, in __init__
        self._open()
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/netmiko/base_connection.py", line 351, in _open
        self.establish_connection()
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/netmiko/base_connection.py", line 920, in establish_connection
        self.remote_conn_pre.connect(**ssh_connect_params)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/client.py", line 406, in connect
        t.start_client(timeout=timeout)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/transport.py", line 660, in start_client
        raise e
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/transport.py", line 2075, in run
        self.kex_engine.parse_next(ptype, m)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/kex_gex.py", line 101, in parse_next
        return self._parse_kexdh_gex_reply(m)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/kex_gex.py", line 281, in _parse_kexdh_gex_reply
        self.transport._verify_key(host_key, sig)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/transport.py", line 1886, in _verify_key
        if not key.verify_ssh_sig(self.H, Message(sig)):
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/paramiko/dsskey.py", line 153, in verify_ssh_sig
        ).public_key(backend=default_backend())
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 212, in public_key
        return backend.load_dsa_public_numbers(self)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 873, in load_dsa_public_numbers
        dsa._check_dsa_parameters(numbers.parameter_numbers)
      File "/root/VirtualEnv/NetAutomation/lib/python3.6/site-packages/netmiko/tplink/tplink_jetstream.py", line 145, in _override_check_dsa_parameters
        if crypto_utils.bit_length(parameters.q) not in [160, 256]:
    AttributeError: module 'cryptography.utils' has no attribute 'bit_length'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

The only modification in the playbooks is in the hosts line. 
As you can see some switches are OK but others have that MODULE FAILURE message.
I've noticed that the ones that failed have a slightly different OS version (6.7.1). The switches with the 6.7.2 don't have any issues.
Do you think that is the problem?
 
Thank you in advance for your help.

**Comment by gmoisio** [comment]
Hi thank you for your message.
Looking at your error message and as far as I remember, I worked with ALE support on a similar issue. Some Omniswitch older AOS releases used an SSH crypto algorithm that was considered deprecated by Cryptography and Paramiko. I found a bad workaround in enabling the algorithm in the configuration files of your linux Ansible server, but the best would be to update your switches to the last AOS6 release after a Release note checking.
Regards

**Comment by bjom8** [comment]
Thank you for your reply.
I will need to use the workaround as those switches are in production now and they cannot go offline.
I've found this workaround:
-------------------------------------------------------------------------------------------------------------
from cryptography.hazmat.primitives.asymmetric import dsa

def _override_check_dsa_parameters(parameters):
    """Override check_dsa_parameters from cryptography's dsa.py

    Allows for shorter or longer parameters.p to be returned from the server's host key. This is a
    HORRIBLE hack and a security risk, please remove if possible!
    """
    # if utils.bit_length(parameters.p) not in [1024, 2048, 3072]:
        # raise ValueError("p is {}, must be exactly 1024, 2048, or 3072 bits long".format(utils.bit_length(parameters.p)))
    if crypto_utils.bit_length(parameters.q) not in [160, 256]:
        raise ValueError("q must be exactly 160 or 256 bits long")

    if not (1 < parameters.g < parameters.p):
        raise ValueError("g, p don't satisfy 1 < g < p.")

dsa._check_dsa_parameters = _override_check_dsa_parameters

----------------------------------------------------------------------------------------------
But I am still getting the same error. Any thoughts?
Thank you

**Comment by gmoisio** [comment]
Hi, I don(t know, but I would prefer to enable protocol in the openssh configuration file and put something like:

```
Host xx.yy.zz.ww
    HostKeyAlgorithms +ssh-dss

```
in the .ssh/config file.

Regards

**Comment by bjom8** [comment]
Hello, there wasn't a file named "config" in the .ssh folder, but I created one and added the configuration. That didn't work.
Then I've added the following configuration to the file /etc/ssh/ssh_config:
Host *
HostkeyAlgorithms +ssh-dss
PubkeyAcceptedKeyTypes +ssh-dss
MACs hmac-sha1

And it worked for regular ssh, like: ssh admin@xx.yy.zz.ww
but I am still getting the same error when I run the playbook

**Comment by gmoisio** [comment]
Hi, ssh_config is a configuration file dedicated to OpenSSH tools, but not available to SSH outside those cases.
I will try to downgrade a switch and reproduce the issue.
Regards

**Comment by bjom8** [comment]
Thank you very much

**Comment by gmoisio** [comment]
Well, I reproduced the issue. I do not want to add this update in the AOS Ansible Network Module, but you can locally try this workaround in the ansible.roles python files.
In the python module that you are using, you can try to add an additional item in the dictionary:

```
    net_device = {
        'device_type': 'alcatel_aos',
        'ip': module.params['host'],
        'port': module.params['port'],
        'username': module.params['username'],
        'password': module.params['password'],
        'ssh_config_file': '<your config file>',
    }
```

Hope this helps...
Regards

**Comment by bjom8** [comment]
Thank you sir. That did the trick.

**Comment by gmoisio** [comment]
You’re welcome.
Upgrade the switches as soon as possible :-)
